version: "3.9"
services:
  bot:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    network_mode: "host"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
